export const mockSchools = [
  {
    id: 1,
    name: "Fahrschule Schmidt",
    description:
      "Professional driving school with over 20 years of experience. We offer comprehensive training for all license types.",
    email: "info@fahrschule-schmidt.de",
    phone: "+49 30 12345678",
    address: "Berliner Straße 123",
    city: "Berlin",
    image: "/placeholder.svg?height=200&width=400",
    rating: 4.8,
    averagePrice: 1850,
    services: ["Car License (B)", "Motorcycle License (A)", "Refresher Courses", "Intensive Courses"],
    prices: {
      registrationFee: 100,
      theoryLesson: 15,
      drivingLesson: 50,
      nightDriving: 55,
      highwayDriving: 55,
      examFee: 150,
      theoryExam: 80,
    },
  },
  {
    id: 2,
    name: "City Fahrschule",
    description:
      "Modern driving school in the heart of Berlin. We focus on efficient training with the latest teaching methods.",
    email: "contact@city-fahrschule.de",
    phone: "+49 30 87654321",
    address: "Hauptstraße 45",
    city: "Berlin",
    image: "/placeholder.svg?height=200&width=400",
    rating: 4.5,
    averagePrice: 1750,
    services: ["Car License (B)", "Truck License (C)", "Automatic Transmission", "Online Theory"],
    prices: {
      registrationFee: 90,
      theoryLesson: 14,
      drivingLesson: 48,
      nightDriving: 52,
      highwayDriving: 52,
      examFee: 145,
      theoryExam: 75,
    },
  },
  {
    id: 3,
    name: "Drive Easy",
    description: "Stress-free driving lessons with patient instructors. We specialize in helping anxious learners.",
    email: "hello@drive-easy.de",
    phone: "+49 30 55667788",
    address: "Friedrichstraße 78",
    city: "Berlin",
    image: "/placeholder.svg?height=200&width=400",
    rating: 4.9,
    averagePrice: 1950,
    services: ["Car License (B)", "Anxiety Support", "Foreign Language Support", "Refresher Courses"],
    prices: {
      registrationFee: 110,
      theoryLesson: 16,
      drivingLesson: 55,
      nightDriving: 60,
      highwayDriving: 60,
      examFee: 160,
      theoryExam: 85,
    },
  },
  {
    id: 4,
    name: "Fahrschule Express",
    description: "Get your license quickly with our intensive courses. Perfect for busy professionals.",
    email: "info@fahrschule-express.de",
    phone: "+49 89 12345678",
    address: "Marienplatz 10",
    city: "Munich",
    image: "/placeholder.svg?height=200&width=400",
    rating: 4.3,
    averagePrice: 1900,
    services: ["Car License (B)", "Intensive Courses", "Weekend Courses", "English Courses"],
    prices: {
      registrationFee: 120,
      theoryLesson: 15,
      drivingLesson: 52,
      nightDriving: 57,
      highwayDriving: 57,
      examFee: 155,
      theoryExam: 82,
    },
  },
  {
    id: 5,
    name: "Premium Fahrschule",
    description: "Luxury driving school with premium vehicles and experienced instructors.",
    email: "contact@premium-fahrschule.de",
    phone: "+49 89 87654321",
    address: "Leopoldstraße 25",
    city: "Munich",
    image: "/placeholder.svg?height=200&width=400",
    rating: 4.7,
    averagePrice: 2100,
    services: ["Car License (B)", "Motorcycle License (A)", "Luxury Vehicles", "VIP Service"],
    prices: {
      registrationFee: 150,
      theoryLesson: 18,
      drivingLesson: 60,
      nightDriving: 65,
      highwayDriving: 65,
      examFee: 170,
      theoryExam: 90,
    },
  },
  {
    id: 6,
    name: "Eco Fahrschule",
    description: "Environmentally friendly driving school with electric and hybrid vehicles.",
    email: "info@eco-fahrschule.de",
    phone: "+49 40 12345678",
    address: "Reeperbahn 150",
    city: "Hamburg",
    image: "/placeholder.svg?height=200&width=400",
    rating: 4.6,
    averagePrice: 1800,
    services: ["Car License (B)", "Eco-Driving", "Electric Vehicles", "Hybrid Vehicles"],
    prices: {
      registrationFee: 100,
      theoryLesson: 15,
      drivingLesson: 50,
      nightDriving: 55,
      highwayDriving: 55,
      examFee: 150,
      theoryExam: 80,
    },
  },
]
